CREATE TABLE USUARIO(
   ID_USUARIO INT AUTO_INCREMENT NOT NULL,
   NOME_USUARIO varchar(150) NOT NULL,
   SENHA_USUARIO varchar(17) NOT NULL,
   UNIVERSIDADE_USUARIO varchar(30) NOT NULL,
   EMAIL_USUARIO varchar(30) NOT NULL,
   CONSTRAINT id PRIMARY KEY (id_usuario)
);

CREATE TABLE EXAME (
   ID_USUARIO INT AUTO INCREMENT NOT NULL,
   NOME_EXAME varchar(20) NOT NULL,
   DATA_EXAME date NOT NULL,
   CONSTRAINT Exame_pk PRIMARY KEY (id_exame)
);

CREATE TABLE TAREFA (
   ID_TAREFA int NOT NULL,
   NOME_TAREFA varchar(%200) NOT NULL,
   ASSUNTO_TAREFA varchar(%200) NOT NULL,
   ANOTACOES_USUARIO varchar(%200) NOT NULL,
   DATA_TAREFA date NOT NULL,
   CONSTRAINT TAREFA_pk PRIMARY KEY (ID_TAREFA)
);

CREATE TABLE DISCIPLINA (
   ID_DISCIPLINA INT AUTO_INCREMENT int NOT NULL,
   NOME_DISCIPLINA varchar(%200) NOT NULL,
   ASSUNTO_DISCIPLINA varchar(%200) NOT NULL,
   ANOTACOES_DISCIPLINA varchar(%200) NOT NULL,
   DESCRICAO_DISCIPLINA varchar(%200) NOT NULL,
   CONSTRAINT DISCIPLINA_pk PRIMARY KEY (ID_DISCIPLINA)
);



